# source 
# Ollama: https://ollama.com
# Open WebUI: https://openwebui.com
# https://github.com/open-webui/open-webui
# https://github.com/open-webui/open-webui/blob/main/docker-compose.yaml
# docker-compose version 2 is used -> no need for version prop

services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    # source: https://stackoverflow.com/questions/57942371/docker-runtime-cgo-pthread-create-failed-resource-temporarily-unavailable
    # uncomment the 2 following lines to fix "runtime/cgo: pthread_create failed: Operation not permitted" if you have it
    security_opt:
      - seccomp:unconfined
    volumes:
      - ollama:/root/.ollama
#    pull_policy: always  #always pull the image from the registry
#    tty: true  #keep the container running
    ports:
      - 11434:11434
    restart: unless-stopped

  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
#    build:
#      context: .
#      args:
#        OLLAMA_BASE_URL: '/ollama'
#      dockerfile: Dockerfile
    volumes:
      - open-webui:/app/backend/data
    depends_on:
      - ollama
    ports:
#      - ${OPEN_WEBUI_PORT-3000}:8080
      - 3000:8080
    environment:
      - 'OLLAMA_BASE_URL=http://ollama:11434'
#      - 'WEBUI_SECRET_KEY='
#    extra_hosts:
#      - host.docker.internal:host-gateway
    restart: unless-stopped

volumes:
  ollama: {}
  open-webui: {}
